[build]
  command = "npm run build"
  
  publish = "dist"
  
  environment = { NODE_VERSION = "22" }

[build.environment]
  NODE_ENV = "production"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200